---

- name: Install nginx
  apt:
    pkg: nginx
    state: present
  become: yes

- name: Copy nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  become: yes

- name: copy  template  default file to /etc/nginx/sites-available
  template: src=nginx_vhost.j2 dest=/etc/nginx/sites-available/{{ app_name }}.conf
  become: yes

- name: Deleting default nginx site from sites-enabled
  file: path=/etc/nginx/sites-enabled/default state=absent
  become: yes

- name: Deleting default nginx site from sites-available
  file: path=/etc/nginx/sites-available/default state=absent
  become: yes

- name: Links site to default
  file: dest=/etc/nginx/sites-enabled/{{ app_name }}.conf src=/etc/nginx/sites-available/{{ app_name }}.conf state=link
  become: yes

- name: Logrotate config for nginx
  template: src=logratate_nginx.j2 dest=/etc/logrotate.d/nginx
  become: yes

- name: Change permissions for nginx log dir 
  file: dest=/var/log/nginx mode=775
  become: yes
- name: Ensure Nginx service is started
  service: name=nginx state=started enabled=yes
  become: yes

- name: reload nginx
  service: name=nginx state=reloaded
  become: yes
